### ISSUE TITLE
FR: make a babel plugin to do compression in the compile time

### ISSUE THREAD

**Issue by bel3atar** [rse/graphql-query-compress#11]

**Comment by frontendr** [comment]
Your wish is my command.

Check it out on [npm](https://www.npmjs.com/package/babel-plugin-transform-compress-graphql) or [GitHub](https://github.com/frontendr/babel-plugin-transform-compress-graphql).

Thanks to @jaydenseric for reporting the [issue](https://github.com/frontendr/babel-plugin-transform-compress-graphql/issues/2).

@rse would you be so kind to link it from your readme?
