### ISSUE TITLE
Causes validation errors with GraphQL.js v15

### ISSUE THREAD

**Issue by jaydenseric** [rse/graphql-query-compress#14]
GraphQL.js v15 no longer tolerates numbers being followed immediately with letters:

- https://github.com/graphql/graphql-js/releases/tag/v15.0.0
- https://github.com/graphql/graphql-js/pull/2164
- https://github.com/graphql/graphql-spec/pull/601

This package compresses field arguments like this:

```graphql
{
  a(b: 1, c: true)
}
```

To this:

```graphql
{a(b:1c:true)}
```

The `1c` creates a query validation error is it is now invalid GraphQL syntax.

Until this is resolved, `graphql-query-compress` is unsafe to use 😭

**Comment by rse** [comment]
Sorry, I cannot repeat this problem:

```sh
$ cat sample.js 
const compress = require(".")
let query = `{
    a(b: 1, c: true)
}
`
query = compress(query)
console.log(query)
$ node sample.js 
{a(b:1,c:true)}
```

Are you sure the problem is introduced by graphql-query-compress itself in your case?

**Comment by jaydenseric** [comment]
You're right! Sorry for the noise; here is the real issue: https://github.com/frontendr/babel-plugin-transform-compress-graphql/issues/4 .
